### ISSUE TITLE
Update FAKE script

### ISSUE THREAD

**Issue by gsomix** [aardvark-platform/aardvark.docs#19]
FAKE script is outdated and fails on run targets. It seems targets are not updated for .NET Core projects.

**Repro steps**

```
> git clone https://github.com/aardvarkplatform/aardvark.docs.git
> cd aardvark.docs
> .\build.cmd Run_HelloWorld
```

**Expected behavior**

Window with running HelloWorld application

**Actual behavior**

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target               Duration
------               --------
Restore              00:00:02.6882440
Compile              00:00:13.2544624
AddNativeResources   00:00:00.0006768
Default              00:00:00.0001035
Run_HelloWorld       Failure
Total:               00:00:16.0819240
---------------------------------------------------------------------
Status:              Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fake.ProcessHelper.start(Process proc) in D:\code\FAKE\src\app\FakeLib\ProcessHelper.fs:line 45
   at Fake.ProcessHelper.asyncShellExec@461-2.Invoke(Unit unitVar) in D:\code\FAKE\src\app\FakeLib\ProcessHelper.fs:line 465
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at FSI_0005.Build.clo@15.Invoke(Unit unitVar0) in D:\Workspace\aardvark.docs\build.fsx:line 16
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
```

**Related information**
* Windows 10
* .NET Core 2.2.301

**Comment by haraldsteinlechner** [comment]
hi. unfortunately aatdvark.docs seems to be a bit in zombie state which indeed is embarrasing. have you tried walkthrough https://github.com/aardvark-platform/walkthrough and template  . aardvark.base has newest build script which we should port over here.

**Comment by gsomix** [comment]
@haraldsteinlechner I'll try. Thanks!

**Comment by haraldsteinlechner** [comment]
aardvark.base has the newest build script with newest fake. this would be
best :)

Evgeniy Andreev <notifications@github.com> schrieb am Mi., 31. Juli 2019,
18:39:

**Comment by haraldsteinlechner** [comment]
oh. docs might also reference old packages in paket. dependencies. i just
upgraded walkthroug today - this one is on head packages...


i am currently on my mobile but well an upgrade would be awesome

Harald Steinlechner <haraldsteinlechner@gmail.com> schrieb am Mi., 31. Juli
2019, 18:41:
